### ISSUE TITLE
Issue with Port and 'additional properties'

### ISSUE THREAD

**Issue by snarknesor** [BewhiskeredBard/homebridge-alexa-player#102]
I am having issues with installation of the plugin, part of which might be a result of me not using the right port? For the authentication, I am using the 'server port' which is 80. I've also tried using the service port according to HOOBS . The log keeps showing this error:
 
_[AlexaPlayer] Error: Configuration error: config should NOT have additional properties_

The only properties I have are platform, amazon domain, client host and port. 

thanks for the help

**Comment by BewhiskeredBard** [comment]
It sounds like you have something like:

```
{
  "platforms": [
    {
      "platform": "AlexaPlayer",
      "amazonDomain": "amazon.com",
      "clientHost": "192.168.1.234",
      "port": 80
    }
  ]
}
```

…instead of…

```
{
  "platforms": [
    {
      "platform": "AlexaPlayer",
      "amazonDomain": "amazon.com",
      "auth": {
        "proxy": {
          "clientHost": "192.168.1.234",
          "port": 80
        }
      }
    }
  ]
}
```

Also, you shouldn't be using port 80. You should be using a new random port (e.g., 2345) that this plug-in will spin up a proxy server on, and then you access http://{CLIENT_HOST}:2345/ to authenticate the plug-in.

**Comment by snarknesor** [comment]
Thanks. Should I be using a random client host as well or using the one that HOOBS is running on?

**Comment by BewhiskeredBard** [comment]
You should use the hostname or IP address that HOOBS is running on.
