### ISSUE TITLE
Intercom/dropin 

### ISSUE THREAD

**Issue by gavinkleckner** [BewhiskeredBard/homebridge-alexa-player#114]
I was wondering if it would be possible to eventually add intercom so you could click intercom on the HomeKit app and it drops in to the echos

**Comment by Chris4285** [comment]
For a speaker service, that is not possible. It has to be a camera which I doubt will be made or it has to be a HomePod which you can't recreate that service.

**Comment by BewhiskeredBard** [comment]
Until NodeHAP provides the underpinnings for this (which seems highly unlikely), I have no plans to attempt supporting it.
