### ISSUE TITLE
Config Setup

### ISSUE THREAD

**Issue by hugomarf** [BewhiskeredBard/homebridge-alexa-player#125]
### Description
I'm new to homebridge and have tried to install this plugin, however, when it runs it produces an error that says amazonDomain is not present.
`[AlexaPlayer] Error: Configuration error: config should have required property 'amazonDomain'`
When I add this to the config, I get this error:
`[AlexaPlayer] Error: Configuration error: config should NOT have additional properties`

Any help would be greatly appreciated

**Comment by gavinkleckner** [comment]
For Amazon domain that depends on what country you’re in so for the United States where I am you choose amazon.com or if you’re in the UK you might choose amazon.co.uk it should be the first drop down menu in the UI 
![628F14F3-62BF-4D8F-8709-9C29E2BBD989](https://user-images.githubusercontent.com/57422502/107187584-db082400-69ab-11eb-92f7-44da4210cfb7.jpeg)

**Comment by BewhiskeredBard** [comment]
Can you post the plug-in configuration you have that isn't working for you?

**Comment by cmorozcogmailcom** [comment]
i can't get mine to work.

    "platforms": [
        {
            "platform": "homebridge-alexa-player",
            "amazonDomain": "amazon.com",
            "auth": {
                "cookie": "xxxx"
            },
            "screensAsTelevisions": true
        }
    ],
    "platform": "homebridge-alexa-player"
}
