### ISSUE TITLE
AirPlay 2

### ISSUE THREAD

**Issue by Stetocasa** [BewhiskeredBard/homebridge-alexa-player#137]
This is an extraordinary plug-in.
In HomeKit, Alexa speaker works as an Airplay2 speakers with no differences.
Could you work to expanse the use also in iOS? I'm referring to shows as AirPlay speakers also if we launch the music by Music app

**Comment by BewhiskeredBard** [comment]
Unfortunately, this is not possible today. AirPlay 2 hasn't been fully reverse-engineered yet, and there's no support for it in Homebridge. Once those two problems are solved, I'd be happy to reconsider this feature.

**Comment by Stetocasa** [comment]
Airplay2 was cracked already
Please check on google: Shairpor-sync

**Comment by BewhiskeredBard** [comment]
Even if AirPlay 2 was fully supported in Homebridge and this plug-in, you would need a device physically plugged into an Echo's audio input that was running the plug-in in order for AirPlay 2's audio sync to work.
