### ISSUE TITLE
Echo does not act as speaker for other HomeKit audio sources

### ISSUE THREAD

**Issue by ghub993** [BewhiskeredBard/homebridge-alexa-player#316]
### Description
Echo only plays local music (from Amazon). It does not act as a "dumb" speaker that can be selected as part of speaker group to play whatever HomeKit Audi source is (in my case either HomePod or AppleTV)

**Comment by BewhiskeredBard** [comment]
That’s not possible with the current state of HomeKit, AirPlay 2, and the available Alexa APIs.
