### ISSUE TITLE
Only finding echo dot

### ISSUE THREAD

**Issue by roberkane212** [BewhiskeredBard/homebridge-alexa-player#429]
I see that others have all their Alexa devices found. Including fire tv devices. I have 2 fire tv devices. Wondering if there’s something else I need to do to find them

**Comment by BewhiskeredBard** [comment]
Are they all registered to the same Amazon account?

**Comment by roberkane212** [comment]
@BewhiskeredBard yes they are all registered to the same account

**Comment by BewhiskeredBard** [comment]
Can you enable debug logging? There should be output in the logs from this plug-in that lists all devices and why they were filtered out.

**Comment by roberkane212** [comment]
@BewhiskeredBard well that’s it, only the echo shows up in logs

**Comment by roberkane212** [comment]
@BewhiskeredBard ok I have them and they are coming up in debug log. However nothing saying why they aren’t showing up

**Comment by roberkane212** [comment]
@BewhiskeredBard they are all being filtered

**Comment by BewhiskeredBard** [comment]
Can you paste the log?
