### ISSUE TITLE
Non-Amazon.com users cannot use cookie config

### ISSUE THREAD

**Issue by QuaCKeReD** [BewhiskeredBard/homebridge-alexa-player#43]
### Description
Adding cookie values to config causes errors

### Reproduction Steps
1. Start HB, with plugin installed
2. click link provided in log, advising to manually obtain cookie
3. add cookie to config
4. restart HB

### Expected Behavior
Adding cookie shouldn't produce error

### Logs
These lines keep flooding logs after startup;

[11/27/2020, 2:16:13 PM] [AlexaPlayer] Failed to initialize. Error: Error while checking Authentication: Error: COnnection Closed
    at /usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:152:49
    at /usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:885:24
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:865:17)
    at ClientRequest.emit (node:events:376:20)
    at TLSSocket.socketCloseListener (node:_http_client:446:9)
    at TLSSocket.emit (node:events:388:22)
    at node:net:661:12
    at TCP.done (node:_tls_wrap:564:7)

### Additional Context
I have ran the proxy link and obtained following in log;

[11/27/2020, 2:46:03 PM] [AlexaPlayer] Alexa cookie retrieved successfully. Save this value in the Homebridge AlexaPlayer configuration as auth.cookie, but never share it with anyone: xxx
[11/27/2020, 2:46:04 PM] Echo is running on port 60597.
[11/27/2020, 2:46:04 PM] Please add [Echo] manually in Home app. Setup Code: 111-22-333

I have tried adding cookie value before and after proxy values, with no change

"platform": "AlexaPlayer",
  "auth": {
    "proxy": {
      "clientHost": "localhost",
      "port": 5678
    },
    "cookie": "session-id=111-22-333; session-id-time=2237206460l; ubid-acbuk=111-222-333; x-acbuk=abcdef; at-acbuk=abcdef; sess-at-acbuk=fcFtabcdef; csrf=999"
}

"platform": "AlexaPlayer",
  "auth": {
    "cookie": "session-id=111-22-333; session-id-time=2237206460l; ubid-acbuk=111-222-333; x-acbuk=abcdef; at-acbuk=abcdef; sess-at-acbuk=fcFtabcdef; csrf=999",
    "proxy": {
      "clientHost": "localhost",
      "port": 5678
    }
}

**Comment by jordanryanmoore** [comment]
Do you live in the UK or use Amazon.co.uk as your Amazon website?

**Comment by jordanryanmoore** [comment]
Also, does the plug-in work for you if you just log in via the proxy without saving the cookie value?

**Comment by QuaCKeReD** [comment]
Hiya,

Yes and yes..... :)

**Comment by jordanryanmoore** [comment]
I'll need to spend some time digging into this then, hopefully this weekend.

**Comment by QuaCKeReD** [comment]
Thanks.

Anything I can do to help?

**Comment by itshusi** [comment]
Hi I'm using UK Amazon and I am also getting the same errors as per @QuaCKeReD when using the cookie value.

**Comment by BewhiskeredBard** [comment]
> Thanks.
> 
> Anything I can do to help?
> 

Not yet. I'm currently refactoring the authentication. Once that's complete, I will need some help with testing.

**Comment by hasnat** [comment]
if one wants to get it working for UK
vi /homebridge/node_modules/homebridge-alexa-player/lib/alexaPlatformPlugin.js
change `PROXY_SERVICE_HOST_DEFAULT` and `SERVICE_HOST_DEFAULT` to .co.uk
am sure refactored authentication would handle regions
```
// - AUDIO_CONTROLS (echo, Sonos Beam)
// - AUDIO_PLAYER (echo, Sonos)
// - DS_VOLUME_SETTING (echo)
AlexaPlatformPlugin.REQUIRED_DEVICE_CAPABILTIES = ['DS_VOLUME_SETTING', 'AUDIO_PLAYER'];
AlexaPlatformPlugin.PROXY_SERVICE_HOST_DEFAULT = 'amazon.co.uk';
AlexaPlatformPlugin.PROXY_LANGUAGE = 'en_US';
AlexaPlatformPlugin.SERVICE_HOST_DEFAULT = 'alexa.amazon.co.uk';
AlexaPlatformPlugin.SERVICE_LANGUAGE = 'en-US';
//# sourceMappingURL=alexaPlatformPlugin.js.map
```

**Comment by itshusi** [comment]
> if one wants to get it working for UK
> vi /homebridge/node_modules/homebridge-alexa-player/lib/alexaPlatformPlugin.js
> change `PROXY_SERVICE_HOST_DEFAULT` and `SERVICE_HOST_DEFAULT` to .co.uk
> am sure refactored authentication would handle regions
> 
> ```
> // - AUDIO_CONTROLS (echo, Sonos Beam)
> // - AUDIO_PLAYER (echo, Sonos)
> // - DS_VOLUME_SETTING (echo)
> AlexaPlatformPlugin.REQUIRED_DEVICE_CAPABILTIES = ['DS_VOLUME_SETTING', 'AUDIO_PLAYER'];
> AlexaPlatformPlugin.PROXY_SERVICE_HOST_DEFAULT = 'amazon.co.uk';
> AlexaPlatformPlugin.PROXY_LANGUAGE = 'en_US';
> AlexaPlatformPlugin.SERVICE_HOST_DEFAULT = 'alexa.amazon.co.uk';
> AlexaPlatformPlugin.SERVICE_LANGUAGE = 'en-US';
> //# sourceMappingURL=alexaPlatformPlugin.js.map
> ```

Thanks for this it worked for me. My saved cookie is now working.

**Comment by BewhiskeredBard** [comment]
The fix was released in v0.5.0.

**Comment by haid45** [comment]
Please consider adding support for amazon.com.au

**Comment by ghub993** [comment]
second that. It would be great to have amazon.com.au
