### ISSUE TITLE
Where to find Alexa Cookie and Auth

### ISSUE THREAD

**Issue by Chris4285** [BewhiskeredBard/homebridge-alexa-player#59]
Hi All,

I really want to try out this plugin but I am confused as to how I can find my cookies for my Alexa. My current setup is:

{
  "platforms": [
    {
      "platform": "AlexaPlayer",
      "auth": {
        "proxy": {
          "clientHost": "{HB IP}",
          "port": {HB Port}
        }
      }
    }
  ]
}

[AlexaPlayer] Failed to initialize. Error: You can try to get the cookie manually by opening http://{ip}:{port}/ with your browser.
    at /usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:387:38
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/lib/proxy.js:366:30)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

which redirected me to my HB UI

**Comment by BewhiskeredBard** [comment]
The port should be a different port than your homebridge UI port (pick anything, e.g., 25392), and then open that hostname:port.

**Comment by Doubledeucedavis** [comment]
I did this and I got "This Page is'nt Working"
"192.168.1.137 sent an invalid response"
