### ISSUE TITLE
Can't control Echo Speakers in Home app

### ISSUE THREAD

**Issue by itshusi** [BewhiskeredBard/homebridge-alexa-player#75]
It seems that none of my Echo devices are working. 
They add to my Home app and display 'Playing/Paused/Stopped' but there is no ability to control any of my alexa devices as you can see here:
![IMG_0408](https://user-images.githubusercontent.com/9934366/102699560-95e23400-423d-11eb-9d16-1c451868ebb9.jpeg)
![IMG_0409](https://user-images.githubusercontent.com/9934366/102699563-98dd2480-423d-11eb-9631-ca20b1167263.jpeg)

Debugged Homebridge logs just outputs a json log for the devices on the account - i.e. _**Creating accessory for device: {"accountName":"Double Room Echo"**_
There are no errors or output even when trying to interact with the speakers in the home app.

**Comment by Chris4285** [comment]
You can't control them yet, @BewhiskeredBard didn't add that feature yet. You can only play/pause.

**Comment by Chris4285** [comment]
Off topic; is that Outlet Homekit native?

**Comment by BewhiskeredBard** [comment]
The Home app controls are extremely limited unless the speaker also implements AirPlay 2 support, which hasn't even been reverse-engineered yet, let alone implemented by Homebridge.

Here's what the Home app does allow you to do:

* Using the speaker tile, you can tap to play/pause.
* Using scenes and automations, you can control play/pause, mute/unmute, and volume.

**Comment by itshusi** [comment]
@Chris4285 Its not - its a TPLink outlet connected via homebridge

@BewhiskeredBard Thanks for clarifying that, it seems as if my play/pause via the tiles doesn't work as when I do press it I get the spinning progress animation but it does nothing.

**Comment by BewhiskeredBard** [comment]
Ah, my bad. That's a bug then.

**Comment by fabian8u** [comment]
I have a similar problem. I‘ve managed to add my Echo Show 5 to HomeKit, but nothing happens when I activate or deactivate the tile. It also doesn‘t match the actual status of my Echo, meaning that it stays „off“ even though music is playing.
Then I disabled the “Screens as Televisions” setting and now HomeKit shows wether the Echo is playing or paused. But when I tap the tile, I get the spinning progress animation but nothing happens.

**Comment by itshusi** [comment]
I have managed to fix this using the fix mentioned in the non amazon.com cookie issue.

The only difference was the location of the file was:
**_/usr/lib/node_modules/homebridge-alexa-player/lib/alexaPlatformPlugin.js_**

> if one wants to get it working for UK
> vi /homebridge/node_modules/homebridge-alexa-player/lib/alexaPlatformPlugin.js
> change PROXY_SERVICE_HOST_DEFAULT and SERVICE_HOST_DEFAULT to .co.uk
> am sure refactored authentication would handle regions
> 
>```
> // - AUDIO_CONTROLS (echo, Sonos Beam)
> // - AUDIO_PLAYER (echo, Sonos)
> // - DS_VOLUME_SETTING (echo)
> AlexaPlatformPlugin.REQUIRED_DEVICE_CAPABILTIES = ['DS_VOLUME_SETTING', 'AUDIO_PLAYER'];
> AlexaPlatformPlugin.PROXY_SERVICE_HOST_DEFAULT = 'amazon.co.uk';
> AlexaPlatformPlugin.PROXY_LANGUAGE = 'en_US';
> AlexaPlatformPlugin.SERVICE_HOST_DEFAULT = 'alexa.amazon.co.uk';
> AlexaPlatformPlugin.SERVICE_LANGUAGE = 'en-US';
> //# sourceMappingURL=alexaPlatformPlugin.js.map
>```

**Comment by fabian8u** [comment]
Worked for me as well with 'amazon.de'/'alexa.amazon.de' as well as changing the language to 'de-DE'.
Thanks a lot!

**Comment by BewhiskeredBard** [comment]
I'll try to get a release out in the next few days that adds these to config instead of having them hard-coded.

**Comment by BewhiskeredBard** [comment]
Release [v0.5.0](https://github.com/BewhiskeredBard/homebridge-alexa-player/releases/tag/v0.5.0) fixed support for non-amazon.com devices. If anyone is still having problems, please open another issue.
